# Generated by Django 3.2.4 on 2021-06-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.CharField(max_length=3)),
                ('path', models.CharField(max_length=100)),
                ('file', models.CharField(max_length=2000)),
            ],
        ),
    ]
